### ISSUE TITLE
Nested Beam Rendering Bug

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#58]
The following Snippet shows a repeating bar where the durations are the same but the beaming is notated differently. It should lead to the same result but the DURATION in the first bar is incorrect.

<code>{ [ \staff<1> 
    \beamBegin:1 f/16 \tieEnd \beamBegin:2 f/32 g/32 \beamEnd:2 f/8 \beamEnd:1 \bar 
\beamBegin:1 f/16 \tieEnd  f/32 g/32  f/8 \beamEnd:1 ]
 }</code>

See screenshot:
<img width="445" alt="screen shot 2018-09-17 at 15 34 25" src="https://user-images.githubusercontent.com/3298204/45626228-45446500-ba8f-11e8-9d09-ffa2936a0bf2.png">

**Comment by arshiacont** [comment]
Any chance of reviewing or guiding the correction of this bug?

**Comment by dfober** [comment]
It's on hold in my schedule. Nevertheless, I recommend not to nest the beams, although this should be addressed by the engine. I'll keep you informed.

**Comment by arshiacont** [comment]
Thank you @dfober 
I am now evading Nested Beam creation in xml2guido which I will push to libmusicxml soon. Thanks for your feedback. 
So this Issue just boils down to _undefined rendering behavior for nested beams_ which can be avoided in my case.

**Comment by dfober** [comment]
The problem is not so easy after all. The main issue is the _mess_ with the different layers of the implementation. My feeling is that it deserves a complete rewriting... Even the semantic of the operation is not clear to me (of course not at musical level). Note that there are several workarounds:
- when `\beamBegin:1 f/16 \tieEnd \beamBegin:2 f/32 g \beamEnd:2 f/8 \beamEnd:1` fails, `\beamBegin:1 f/16 \tieEnd f/32 g f/8 \beamEnd:1` is correct
- similarly, `\beamBegin:1  \beamBegin:2 f/16 \beamBegin:3 f/32 g \beamEnd:2 \beamEnd:3 f/8 \beamEnd:1` is also correct
The same is true with the parenthesis form:
- when `\beam( f/16 \beam( f/32 g ) f/8 )` fails, `\beam( f/16  f/32 g  f/8 )` is correct
- and, `\beam( \beam(f/16 \beam( f/32 g )) f/8 )`too

Thus, if you let the engine do (with a minimum of indications) everything is fine,
otherwise you have to add a beaming layer for the missing one.

**Comment by arshiacont** [comment]
@dfober I would like to revive this issue at some point... :

Nested beams are actually useful in Guido if you want to render sth like this:
![Screenshot 2019-05-03 at 10 08 43](https://user-images.githubusercontent.com/3298204/57125914-7443e880-6d8b-11e9-9eee-24b67b0d3f74.png)

which is only possible if you nest Beams like this in Guido:
```
{[ \staff<1> 
   (* meas. 1 *)  \clef<"g2"> \key<0> \meter<"3/8">  
\beamBegin:1 \beam(c2/16 a1/16  c2/16  e&/16) \beamBegin:2 \tuplet<"3", dispNote="/16", position="below">( f#/24 a/24 c3/24) \beamEnd:2
 \beamEnd:1 \bar 
   (* meas. 2 *)  \stemsDown \beamBegin:1  \beamBegin:2 c2/16 \stemsDown a1/16 \beamEnd:2 
\beamBegin:2 \tuplet<"3", dispNote="/16", position="below">( c2/24 e&/24 f#/24) \beamEnd:2 
\beamBegin:2 a/16 c3/16 \beamEnd:2 \beamEnd:1 ]
  }
```

While this renders fine, we still have the old Bug above, where nested beaming somehow changes the "duration".

**Comment by arshiacont** [comment]
In case it helps, here is another unit test with current result and expected behaviour. Problem is visible on the first 5 notes of each measure. Excerpt taken from Violin solo of Vivaldi Autumn movement 3:

```
{[ \staff<1> 
   \clef<"g2"> \key<-1> \meter<"3/8">  
   (* meas. 1 *)  \stemsDown \beamBegin:1 \tuplet<"3", dispNote="/16", position="below">( c3/24 \stemsDown \slurBegin:1<curve="up"> \beamBegin:2  b2/48 \stemsDown a/48 \stemsDown g/48 \stemsDown f/48) \beamEnd:1 \beamEnd:2 
\stemsDown \beamBegin:1 \tuplet<"3", dispNote="/16", position="below">( e/24 \stemsDown d/24 \stemsDown c/24) \slurEnd:1  \beamEnd:1 
\stemsDown \slurBegin:1<curve="up"> \beamBegin:1 \tuplet<"3", dispNote="/16">( e/24 \stemsDown g/24 \stemsDown b&/24)
 \slurEnd:1 \beamEnd:1 \bar 
   (* meas. 2 *)  \stemsDown \beamBegin:1 \tuplet<"3", dispNote="/16", position="below">( d3/24 \stemsDown \slurBegin:1<curve="up"> \beamBegin:2 c/48 \stemsDown b&2/48 \stemsDown a/48 \stemsDown g/48)
 \beamEnd:2 \beamEnd:1 \stemsDown \beamBegin:1 \tuplet<"3", dispNote="/16", position="below">( f#/24 \stemsDown e/24 \stemsDown d/24)
 \slurEnd:1 \beamEnd:1 \stemsDown \slurBegin:1<curve="up"> \beamBegin:1 \tuplet<"3", dispNote="/16">( f#/24 \stemsDown a/24 \stemsDown c3/24)
 \slurEnd:1 \beamEnd:1 
 ]
  }
``` 
Current result:
![image](https://user-images.githubusercontent.com/3298204/59261990-4310d080-8bf3-11e9-90a2-638ddcf51750.png)

Expected behaviour:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/3298204/59262033-52901980-8bf3-11e9-8291-cef9ea4e11bb.png">

**Comment by arshiacont** [comment]
@dfober If you can guide us on where to look into to fix this, I am willing to give it a go

**Comment by dfober** [comment]
Just remove the dispNote and you'll get a correct result. It enforces all notes appearance whatever their duration. It's similar to \dispDur tag that can be used anywhere.
`{
[ 
	\staff<1> 
	\clef<"g2"> \key<-1> \meter<"3/8">  
   (* meas. 1 *)  \beamBegin:1 
	\tuplet<"3", position="below">( c3/24 \slurBegin:1<curve="up"> 
	\beamBegin:2  b2/48 a g f) \beamEnd:1 \beamEnd:2 
	
	\beamBegin:1 \tuplet<"3", dispNote="/16", position="below">( e/24 
	d/24 c/24) \slurEnd:1  \beamEnd:1 
	\slurBegin:1<curve="up"> 
	\beamBegin:1 \tuplet<"3">( e/24 g b&) \slurEnd:1 \beamEnd:1 \bar 
   
	(* meas. 2 *)  \beamBegin:1 \tuplet<"3",position="below">( d3/24 
	\slurBegin:1<curve="up"> \beamBegin:2 c/48 b&2/48 a/48 g/48)
 	\beamEnd:2 \beamEnd:1 
 	\beamBegin:1 \tuplet<"3", position="below">( f#/24 e/24 d/24)
 	\slurEnd:1 \beamEnd:1 \slurBegin:1<curve="up"> 
	\beamBegin:1 \tuplet<"3">( f#/24 a/24 c3/24)
 	\slurEnd:1 \beamEnd:1 
]
}`

**Comment by arshiacont** [comment]
Thank you @dfober .

When do you recommend actually using `dispNote` in Tuplets? (intended for xml2GUIDO)

Regarding this ticket, we then only have the initial issue as reported above (https://github.com/grame-cncm/guidolib/issues/58#issue-360872577) that needs to be addressed. I had disabled nested beaming in xml2guido because of that. If there's anything I can do to dive into that issue, do not hesitate to send me pointers.

**Comment by dfober** [comment]
> When do you recommend actually using dispNote in Tuplets? (intended for xml2GUIDO)

Don't really know. I would have said if you want to make special scores...

Regarding the issue, I'll have a look asap but I'm currently quite busy
.

**Comment by arshiacont** [comment]
@dfober After tests and comparisons, here is what I think the rational for dispNote in Tuplet is: Tuplets in Guido just nest notes and chords. They are not aware of the "time-modification" (as in MusicXML). Thus the duration of notes inside the chord will not coincide with anything that Guido knows about to render their stems according to duration.
Example: On a 2/4 measure which has a tuplet covering the entire measure with 27 notes, you can notate it as "27 32nd notes in place of 16 32nd". Durations in Guido will be `/54` and Guido won't render those notes as 32nd. That's when `dispNote` saves the rendering.
There is nothing "special" to this since as soon as you make tuplets with Prime numbers as seen in a lot of Classical repertoire (including Vivaldi, not to mention Ravel etc).

**Comment by arshiacont** [comment]
Looking forward to working with you on this issue (which comes from Ravel) in a few weeks! ;)

**Comment by arshiacont** [comment]
@dfober I am going to close this Ticket. The following example shows the correct Beam syntax in Guido where the 2nd measure is wrong and the 3rd is correct (which becomes equal to the first):
```
{ [ \staff<1> \beamBegin:1 f/16 \tieEnd \beamBegin:2 f/32 g/32 \beamEnd:2 f/8 \beamEnd:1 \bar 
\beamBegin:1 f/16 \tieEnd f/32 g/32 f/8 \beamEnd:1 \bar
 \beamBegin:1 \beamBegin:2 f/16 \tieEnd \beamBegin:3 f/32 g/32 \beamEnd:3 \beamEnd:2 f/8 \beamEnd:1 ] }
```

This means that in Guido terminology Beams more or less correspond to the Beam Lines! The syntax might be redundant but at least it is coherent with other standards such as MusicXML.

![image](https://user-images.githubusercontent.com/3298204/62793026-e20d5800-bad0-11e9-96b4-b72f31d3d823.png)
